title: szingaro.github.io
author:
  name: szingaro
  email: 
description: > # this means to ignore newlines until "show_excerpts:"
  This website is just a placeholder to collect links of repositories in my GitHub profile.

show_excerpts: true

# Minima date format
minima:
  date_format: "%b %-d, %Y"

#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
