title: szingaro.github.io
description: > # this means to ignore newlines until "show_excerpts:"
  This website is just a placeholder to collect links of repositories in my GitHub profile.

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
